name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build image
      env:
        TAG: ${{github.event.release.tag_name}}
      run: docker build . --file Dockerfile --tag ericmiguel/alpine-conda:$TAG
    - name: push
      run: docker push ${{secrets.DOCKER_USER}}/alpine-conda
